import Breadcrumbs from "@/components/forums/Account/Breadcrumb";
import { SideBar } from "@/components/forums/Account/SideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "My Account - TheDemonTuan",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className="lg:flex lg_max:space-y-5 p-5">
			<SideBar />
			<div className="lg:flex-auto bg-forum_white rounded-2xl p-5 lg_max:shadow-2xl z-10">
				<Breadcrumbs />
				{children}
			</div>
		</div>
	);
}
