"use client";

import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Metadata } from "next";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({
	subsets: ["latin"],
	preload: true,
	weight: ["400"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "TheDemonTuan - Forum",
	description: "Generated by create next app",
};

const queryClient = new QueryClient();
export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<QueryClientProvider client={queryClient}>
					{children}
					<ReactQueryDevtools initialIsOpen={false} />
				</QueryClientProvider>
			</body>
		</html>
	);
}
